# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 FÃ©lix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Unit tests'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  unit-tests:
    name: 'Unit tests'
    uses: sequentech/meta/.github/workflows/unit-tests.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
      rust: true
      rust-command: 'cargo test'
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
